# Generated by Django 4.0 on 2022-07-11 11:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoshuinBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.users')),
            ],
            options={
                'db_table': 'goshuin_books',
            },
        ),
        migrations.CreateModel(
            name='Goshuins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateField(default=datetime.date(2022, 7, 11))),
                ('picture', models.FileField(upload_to='goshuin_pictures')),
                ('memo', models.CharField(blank=True, max_length=255)),
                ('goshuin_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goshuin_books.goshuinbooks')),
            ],
            options={
                'db_table': 'goshuins',
            },
        ),
    ]
